service: hello-world-typescript

provider:
  name: aws 
  runtime: nodejs12.x 
  stage: dev 
  memorySize: 512 # Default is 1024.
  timeout: 30 

plugins:
  # temp fix to hot reload issue (see https://github.com/dherault/serverless-offline/issues/864)
  # is --useChildProcesses flag (see package.json) 
  - serverless-plugin-typescript
  - serverless-offline

functions:
  helloWord:
    handler: index.helloWorld
    events:
      - http: get hello-world
